export interface StatementData {
  nodeId: string
  walletAddress: string
  gpuTier: string
  periodStart: string
  periodEnd: string
  totalEarnings: number
  totalJobs: number
  totalGpuHours: number
  settlements: {
    id: string
    amount: number
    status: string
    txHash?: string
    processedAt?: string
  }[]
  dailyEarnings: {
    date: string
    market: string
    earnings: number
    jobCount: number
  }[]
}

export interface InvoiceData {
  invoiceNumber: string
  customerId: string
  customerName: string
  periodStart: string
  periodEnd: string
  lineItems: {
    description: string
    gpuTier: string
    hours: number
    ratePerHour: number
    amount: number
  }[]
  subtotal: number
  tax: number
  total: number
}

export function generateStatementHTML(data: StatementData): string {
  const settlementsHtml = data.settlements
    .map(
      (s) => `
      <tr>
        <td>${s.id.substring(0, 8)}...</td>
        <td>$${s.amount.toFixed(2)}</td>
        <td>${s.status}</td>
        <td>${s.txHash ? s.txHash.substring(0, 16) + '...' : '-'}</td>
        <td>${s.processedAt ?? '-'}</td>
      </tr>
    `
    )
    .join('')

  const earningsHtml = data.dailyEarnings
    .map(
      (e) => `
      <tr>
        <td>${e.date}</td>
        <td>${e.market}</td>
        <td>$${e.earnings.toFixed(2)}</td>
        <td>${e.jobCount}</td>
      </tr>
    `
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Earnings Statement - ${data.nodeId}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
    h2 { color: #4f46e5; margin-top: 30px; }
    .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
    .summary { background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
    .summary-item { text-align: center; }
    .summary-value { font-size: 24px; font-weight: bold; color: #6366f1; }
    .summary-label { color: #64748b; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>Earnings Statement</h1>
      <p><strong>Node:</strong> ${data.nodeId}</p>
      <p><strong>Wallet:</strong> ${data.walletAddress}</p>
      <p><strong>GPU Tier:</strong> ${data.gpuTier}</p>
    </div>
    <div style="text-align: right;">
      <p><strong>Period:</strong></p>
      <p>${data.periodStart} - ${data.periodEnd}</p>
      <p><strong>Generated:</strong> ${new Date().toISOString().split('T')[0]}</p>
    </div>
  </div>

  <div class="summary">
    <div class="summary-grid">
      <div class="summary-item">
        <div class="summary-value">$${data.totalEarnings.toFixed(2)}</div>
        <div class="summary-label">Total Earnings</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${data.totalJobs}</div>
        <div class="summary-label">Jobs Completed</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${data.totalGpuHours.toFixed(1)}</div>
        <div class="summary-label">GPU Hours</div>
      </div>
    </div>
  </div>

  <h2>Settlement History</h2>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Amount</th>
        <th>Status</th>
        <th>TX Hash</th>
        <th>Processed</th>
      </tr>
    </thead>
    <tbody>
      ${settlementsHtml || '<tr><td colspan="5">No settlements in this period</td></tr>'}
    </tbody>
  </table>

  <h2>Daily Earnings</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Market</th>
        <th>Earnings</th>
        <th>Jobs</th>
      </tr>
    </thead>
    <tbody>
      ${earningsHtml || '<tr><td colspan="4">No earnings in this period</td></tr>'}
    </tbody>
  </table>

  <div class="footer">
    <p>This statement is auto-generated by the A²E Engine.</p>
    <p>For questions, contact support@tokenos.ai</p>
  </div>
</body>
</html>
`
}

export function generateInvoiceHTML(data: InvoiceData): string {
  const lineItemsHtml = data.lineItems
    .map(
      (item) => `
      <tr>
        <td>${item.description}</td>
        <td>${item.gpuTier}</td>
        <td>${item.hours.toFixed(2)}</td>
        <td>$${item.ratePerHour.toFixed(2)}</td>
        <td>$${item.amount.toFixed(2)}</td>
      </tr>
    `
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Invoice ${data.invoiceNumber}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1a1a2e; }
    .invoice-header { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .invoice-number { font-size: 24px; color: #6366f1; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; }
    .totals { margin-top: 20px; text-align: right; }
    .total-row { display: flex; justify-content: flex-end; gap: 40px; padding: 8px 0; }
    .total-label { color: #64748b; }
    .grand-total { font-size: 20px; font-weight: bold; color: #6366f1; border-top: 2px solid #6366f1; padding-top: 10px; }
    .footer { margin-top: 60px; color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <div class="invoice-header">
    <div>
      <h1>INVOICE</h1>
      <p class="invoice-number">${data.invoiceNumber}</p>
    </div>
    <div style="text-align: right;">
      <p><strong>A²E Engine</strong></p>
      <p>TokenOS Platform</p>
      <p>compute.tokenos.ai</p>
    </div>
  </div>

  <div style="margin-bottom: 30px;">
    <p><strong>Bill To:</strong></p>
    <p>${data.customerName}</p>
    <p>Customer ID: ${data.customerId}</p>
  </div>

  <div style="margin-bottom: 30px;">
    <p><strong>Period:</strong> ${data.periodStart} - ${data.periodEnd}</p>
    <p><strong>Invoice Date:</strong> ${new Date().toISOString().split('T')[0]}</p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>GPU Tier</th>
        <th>Hours</th>
        <th>Rate/Hour</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      ${lineItemsHtml}
    </tbody>
  </table>

  <div class="totals">
    <div class="total-row">
      <span class="total-label">Subtotal:</span>
      <span>$${data.subtotal.toFixed(2)}</span>
    </div>
    <div class="total-row">
      <span class="total-label">Tax:</span>
      <span>$${data.tax.toFixed(2)}</span>
    </div>
    <div class="total-row grand-total">
      <span>Total:</span>
      <span>$${data.total.toFixed(2)}</span>
    </div>
  </div>

  <div class="footer">
    <p>Payment Terms: Due upon receipt</p>
    <p>Payment Methods: SOL, USDC (Solana)</p>
    <p>Questions? Contact billing@tokenos.ai</p>
  </div>
</body>
</html>
`
}
