/**
 * Launch-blocker #2 — agent-side ephemeral SSH session manager.
 *
 * The API surfaces session actions via the heartbeat response. For each
 * action this module:
 *   - provision: creates a fresh Linux user (rental-<requestId-prefix>),
 *     installs the buyer's authorized public key, reports ACTIVE.
 *   - terminate: kills any processes owned by the user, removes the
 *     user + home dir, reports TERMINATED.
 *
 * Hardening of sshd for these users is one-time and idempotent: on
 * first dispatch we drop a Match-block snippet into
 *   /etc/ssh/sshd_config.d/a2e-rentals.conf
 * and reload sshd. The main sshd_config is never edited.
 *
 * Safety rails:
 *   - linux-only; macOS and Windows hosts log + skip
 *   - requires root (the systemd unit already runs as root)
 *   - username must match /^rental-[a-z0-9]{1,24}$/ — refuse anything
 *     else so a buggy server can never make us delete an operator's
 *     real user account
 *   - all subprocess calls have a hard 10s timeout
 *
 * Concurrency: a single in-process Set tracks request ids we are
 * currently working on so two close-together heartbeats can't try
 * to provision/terminate the same session twice.
 */

import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { apiLogger } from '../utils/logger.js'
import type { ApiClient } from '../api/client.js'
import type { SshSessionAction } from '../api/types.js'

const log = apiLogger()
const exec = promisify(execFile)

const USERNAME_REGEX = /^rental-[a-z0-9]{1,24}$/

const SSHD_DROP_IN_PATH = '/etc/ssh/sshd_config.d/a2e-rentals.conf'
const SSHD_DROP_IN_BODY = `# Generated by a2e-agent (launch-blocker #2).
# Hardens sshd for rental-* users so a buyer can only run an
# interactive shell — no tunneling, no agent forwarding, no X11.

Match User rental-*
    AllowTcpForwarding no
    AllowAgentForwarding no
    X11Forwarding no
    PermitTunnel no
    GatewayPorts no
    AllowStreamLocalForwarding no
    PermitTTY yes
    ForceCommand none
`

const SUBPROCESS_TIMEOUT_MS = 10_000

class SessionError extends Error {
  constructor(public readonly stage: string, message: string) {
    super(message)
    this.name = 'SessionError'
  }
}

export class SshSessionManager {
  private readonly inFlight = new Set<string>()
  private sshdHardeningInstalled = false

  constructor(private readonly api: ApiClient) {}

  /**
   * Single entry point called from the heartbeat sender whenever the
   * API surfaces an sshSession action. Caller does not await — fire
   * and forget; we report back via the status callback.
   */
  dispatch(action: SshSessionAction): void {
    if (this.inFlight.has(action.requestId)) {
      log.debug({ requestId: action.requestId }, 'SSH action already in flight, skipping')
      return
    }
    this.inFlight.add(action.requestId)

    void this.run(action).finally(() => {
      this.inFlight.delete(action.requestId)
    })
  }

  private async run(action: SshSessionAction): Promise<void> {
    if (os.platform() !== 'linux') {
      log.warn(
        { requestId: action.requestId, platform: os.platform() },
        'SSH session manager only supports Linux; skipping action'
      )
      await this.reportFailure(action.requestId, `unsupported platform: ${os.platform()}`)
      return
    }
    if (process.getuid?.() !== 0) {
      log.error({ requestId: action.requestId }, 'SSH session manager requires root')
      await this.reportFailure(action.requestId, 'agent not running as root')
      return
    }
    if (!USERNAME_REGEX.test(action.username)) {
      log.error(
        { requestId: action.requestId, username: action.username },
        'SSH session refused: username does not match rental-* pattern'
      )
      await this.reportFailure(action.requestId, `unsafe username: ${action.username}`)
      return
    }

    try {
      await this.ensureSshdHardening()
    } catch (err) {
      log.error({ err }, 'Failed to install sshd hardening drop-in')
      // Hardening failure is non-fatal for provision; the rental still
      // works, just without the lock-down. Continue.
    }

    try {
      if (action.action === 'provision') {
        await this.provision(action.requestId, action.username, action.pubKey)
      } else {
        await this.terminate(action.requestId, action.username)
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      log.error(
        { err, requestId: action.requestId, action: action.action },
        'SSH session operation failed'
      )
      await this.reportFailure(action.requestId, msg)
    }
  }

  private async provision(
    requestId: string,
    username: string,
    pubKey: string | undefined
  ): Promise<void> {
    if (!pubKey) {
      throw new SessionError('validate', 'no pubKey provided for provision')
    }

    await this.api.reportSshSessionStatus(requestId, { status: 'PROVISIONING' })

    // useradd: -m makes the home dir; -s sets a real shell. Ignore
    // exit code 9 (user already exists) so re-provisions stay idempotent.
    await this.runCmd('useradd', ['-m', '-s', '/bin/bash', username]).catch((err) => {
      if (err.code === 9) {
        log.info({ username }, 'Rental user already exists; reusing')
        return
      }
      throw err
    })

    const homeDir = `/home/${username}`
    const sshDir = path.join(homeDir, '.ssh')
    const authKeysPath = path.join(sshDir, 'authorized_keys')

    await fs.mkdir(sshDir, { recursive: true, mode: 0o700 })
    // Single key per rental; overwrite anything that was there. The
    // trailing newline matters — some sshd builds reject the last entry
    // without one.
    const keyBody = pubKey.trim().endsWith('\n') ? pubKey.trim() : `${pubKey.trim()}\n`
    await fs.writeFile(authKeysPath, keyBody, { mode: 0o600 })

    // chown after writing so ownership lands correctly on a fresh dir.
    await this.runCmd('chown', ['-R', `${username}:${username}`, sshDir])
    await this.runCmd('chmod', ['700', sshDir])
    await this.runCmd('chmod', ['600', authKeysPath])

    log.info({ requestId, username }, 'Rental SSH user provisioned')
    await this.api.reportSshSessionStatus(requestId, { status: 'ACTIVE' })
  }

  private async terminate(requestId: string, username: string): Promise<void> {
    // Kill anything the user has running. -KILL is unrecoverable;
    // -u <user> targets by uid. exit 1 just means "no processes found",
    // not an error — buyer may have already disconnected cleanly.
    await this.runCmd('pkill', ['-KILL', '-u', username]).catch((err) => {
      if (err.code === 1) return
      throw err
    })

    // Give the kernel a beat to reap processes before userdel.
    await sleep(500)

    // userdel -r removes the home dir along with the user. exit 6
    // (user does not exist) is fine — idempotent.
    await this.runCmd('userdel', ['-r', username]).catch((err) => {
      if (err.code === 6) {
        log.info({ username }, 'Rental user already gone; nothing to clean up')
        return
      }
      throw err
    })

    log.info({ requestId, username }, 'Rental SSH user torn down')
    await this.api.reportSshSessionStatus(requestId, { status: 'TERMINATED' })
  }

  private async ensureSshdHardening(): Promise<void> {
    if (this.sshdHardeningInstalled) return

    try {
      const existing = await fs.readFile(SSHD_DROP_IN_PATH, 'utf8').catch(() => '')
      if (existing.trim() !== SSHD_DROP_IN_BODY.trim()) {
        await fs.mkdir(path.dirname(SSHD_DROP_IN_PATH), { recursive: true })
        await fs.writeFile(SSHD_DROP_IN_PATH, SSHD_DROP_IN_BODY, { mode: 0o644 })
        log.info({ path: SSHD_DROP_IN_PATH }, 'Installed sshd hardening drop-in')

        // systemctl reload-or-restart sshd. Prefer reload — restart
        // would drop existing buyer SSH sessions which we want to avoid.
        await this.runCmd('systemctl', ['reload', 'ssh']).catch(async () => {
          await this.runCmd('systemctl', ['reload', 'sshd']).catch((err) => {
            log.warn({ err }, 'Failed to reload sshd; drop-in will take effect on next restart')
          })
        })
      }
      this.sshdHardeningInstalled = true
    } catch (err) {
      log.warn({ err }, 'Could not install sshd hardening drop-in')
      throw err
    }
  }

  private async runCmd(cmd: string, args: string[]): Promise<void> {
    try {
      await exec(cmd, args, { timeout: SUBPROCESS_TIMEOUT_MS })
    } catch (err) {
      const e = err as NodeJS.ErrnoException & { code?: number | string }
      throw Object.assign(new SessionError(cmd, e.message || `${cmd} failed`), {
        code: typeof e.code === 'number' ? e.code : Number(e.code) || undefined,
      })
    }
  }

  private async reportFailure(requestId: string, errorMessage: string): Promise<void> {
    try {
      await this.api.reportSshSessionStatus(requestId, {
        status: 'FAILED',
        errorMessage,
      })
    } catch (err) {
      log.error({ err, requestId }, 'Failed to report SSH session FAILED status')
    }
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
